version: '3.8'
services:
  postgres:
    container_name: fitness
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fitness_db'    # Specifies the name of the database to be created
      - 'POSTGRES_PASSWORD=postgres'    # Sets the password for the PostgreSQL user
      - 'POSTGRES_USER=postgres'    # Sets the username for accessing the PostgreSQL database
    ports:
      - '5432:5432'    # Maps the container's PostgreSQL port 5432 to the host's port 5432 for external access

#
#
#
#version: '3.8'
#
#services:
#  postgres:
#    container_name: fitness_postgres
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=fitness_db'    # Specifies the name of the database to be created
#      - 'POSTGRES_PASSWORD=postgres'    # Sets the password for the PostgreSQL user
#      - 'POSTGRES_USER=postgres'    # Sets the username for accessing the PostgreSQL database
#    ports:
#      - '5432:5432'    # Maps the container's PostgreSQL port 5432 to the host's port 5432 for external access
