server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296

  cloud:
    gateway:
      routes:
        - id: MS-PROFILE
          uri: lb://MS-PROFILE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: MS-PROFILE
                fallbackuri: forward:/profileServiceFallback
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1

        - id: MS-FITNESS-PLAN
          uri: lb://MS-FITNESS-PLAN
          predicates:
            - Path=/api/v1/fitness/plans/**
          filters:
            - name: CircuitBreaker
              args:
                name: MS-FITNESS-PLAN
                fallbackuri: forward:/fitnessPlanServiceFallback
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1



#        - id: PRODUCT-SERVICE
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/product/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PRODUCT-SERVICE
#                fallbackuri: forward:/productServiceFallBack
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1